### ISSUE TITLE
Download rebar3.cmd

### ISSUE THREAD

**Issue by AryaanSheth** [AryaanSheth/gloq#2]
```
❯ gleam build
  Compiling certifi
error: Program not found

The program `rebar3.cmd` was not found. Is it installed?
````

https://github.com/erlef/setup-beam/issues/147

**Comment by AryaanSheth** [comment]
FIX:
1. Download rebar3.cmd from chocolatey [here](https://community.chocolatey.org/packages/rebar3#upgrade)
2. Add rebar3.cmd to path

**Comment by edge-rps** [comment]
if rebar3 is working but rebar3.cmd is not working I found a solution, run this in a powershell term as administrator 

```ps
 $rebar = (Get-Command rebar3).Source; $dir = Split-Path $rebar; Set-Content -Path "$dir\rebar3.cmd" -Value "@echo off`n`"$rebar`" %*"
```
